.PHONY: clean All

All:
	@echo "----------Building project:[ PECLGalvezEsquivelJulian - Debug ]----------"
	@cd "PECLGalvezEsquivelJulian" && "$(MAKE)" -f  "PECLGalvezEsquivelJulian.mk"
clean:
	@echo "----------Cleaning project:[ PECLGalvezEsquivelJulian - Debug ]----------"
	@cd "PECLGalvezEsquivelJulian" && "$(MAKE)" -f  "PECLGalvezEsquivelJulian.mk" clean
